name: archiver-CI

on:
  push:
    branches: [main, work]
  pull_request:
    branches: [main]


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt-get install -y cmake gcc

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: test
        run: |
          cd build
          ctest --output-on-failure

  valgrind:
    runs-on: ubuntu-latest

    steps::
      - uses: actions/checkout@v4
      
      - name: install dependencies
        run: sudo apt-get install -y cmake gcc valgrind

      - name: build without sanitizer
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_C_FLAGS=""
          make

      - name: run valgrind
        run: |
          cd build
          valgrind --leak-check=full --error-exitcode=1 ./huffman -e ..exp_files/bigTXT.txt /tmp/out.bin
